README.dev: update prerequisites
Add uuid to the listed prerequisites to
avoid the build error due to a missing include:

fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>

Signed-off-by: Albert Esteve <aesteve@redhat.com>