python: Use error description in SanlockException
When raising SanlockException, if the error code was a posix error, we
included the error description from strerror(3), but for sanlock error
codes we included a rather unhelpful "Sanlock exception".

Now that we have sanlock_strerror() we can use it to include the actual
error description:

    sanlock.SanlockException: (-223, 'Sanlock resource read failure',
    'Lease does not exist on storage')

Signed-off-by: Nir Soffer <nsoffer@redhat.com>