Makefile: %systemd_postun requires arguments now
Since Fedora 31, %system_postun requires arguments, and fail with this
"helpful" message without arguments:

    error: This macro requires some arguments

Signed-off-by: Nir Soffer <nsoffer@redhat.com>